# Generated by Django 4.2.7 on 2023-11-28 07:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparent_power', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('active_power', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('power_factor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('total_ele', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=10)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.roomindexmodel')),
            ],
            options={
                'db_table': 'room_data',
            },
        ),
    ]
