# Generated by Django 4.2.7 on 2023-12-04 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roomhdamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomindexmodel',
            old_name='rid',
            new_name='idc_id',
        ),
    ]
