# Generated by Django 4.2.7 on 2023-11-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_boxalarmmodel_boxindexmodel_delete_baralarmmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='事件类型')),
                ('event_content', models.CharField(blank=True, max_length=128, null=True, verbose_name='事件内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.barindexmodel')),
            ],
            options={
                'db_table': 'bus_bar_event',
            },
        ),
        migrations.RemoveField(
            model_name='boxindexmodel',
            name='bar',
        ),
        migrations.DeleteModel(
            name='BoxAlarmModel',
        ),
        migrations.DeleteModel(
            name='BoxIndexModel',
        ),
    ]
