# Generated by Django 4.2.7 on 2023-11-14 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_boxuutmodel_delete_boxeventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarUutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_sn', models.CharField(max_length=64, null=True, verbose_name='序列号')),
                ('dev_type', models.CharField(max_length=64, null=True, verbose_name='设备型号')),
                ('idc_name', models.CharField(max_length=64, null=True, verbose_name='数据中心')),
                ('room_name', models.CharField(max_length=64, null=True, verbose_name='机房名称')),
                ('cabinet_name', models.CharField(max_length=64, null=True, verbose_name='机柜名称')),
                ('dev_position', models.CharField(max_length=64, null=True, verbose_name='设备位置')),
                ('qrcode', models.CharField(max_length=256, null=True, verbose_name='二维码内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.barindexmodel')),
            ],
            options={
                'db_table': 'bus_bar_uut',
            },
        ),
        migrations.RemoveField(
            model_name='boxuutmodel',
            name='box',
        ),
        migrations.DeleteModel(
            name='BoxIndexModel',
        ),
        migrations.DeleteModel(
            name='BoxUutModel',
        ),
    ]
