# Generated by Django 4.2.7 on 2023-11-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_baruutmodel_remove_boxuutmodel_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barindexmodel',
            name='active_power',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='apparent_power',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='box_num',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='插接箱数量'),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='ip_addr',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='设备地址'),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='power_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='total_ele',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='BarUutModel',
        ),
    ]
