# Generated by Django 4.2.7 on 2023-11-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_barindexmodel_active_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barindexmodel',
            name='breaker_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='current_unbalance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='hz',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='频率'),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='voltage_unbalance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barindexmodel',
            name='zero_line_current',
            field=models.FloatField(default=0),
        ),
    ]
