# Generated by Django 3.2.12 on 2023-10-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxindex',
            name='bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.barindex'),
        ),
    ]
