# Generated by Django 4.2.7 on 2023-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PduIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('run_status', models.PositiveSmallIntegerField(default=0, verbose_name='运行状态')),
                ('apparent_power', models.FloatField(default=0)),
                ('active_power', models.FloatField(default=0)),
                ('power_factor', models.FloatField(default=0)),
                ('total_ele', models.FloatField(default=0)),
                ('ip_addr', models.CharField(max_length=64, null=True, verbose_name='IP地址')),
                ('cascade_addr', models.PositiveSmallIntegerField(default=0, verbose_name='级联地址')),
                ('current_alarm', models.CharField(max_length=256, null=True, verbose_name='当前报警')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pdu_index',
            },
        ),
    ]
