# Generated by Django 4.2.7 on 2023-11-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pduindex',
            old_name='create_time',
            new_name='createtime',
        ),
        migrations.RenameField(
            model_name='pduindex',
            old_name='update_time',
            new_name='updatetime',
        ),
    ]
