# Generated by Django 4.2.7 on 2023-11-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0004_rename_pduhda_pduhdamodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PduEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='事件类型')),
                ('event_content', models.CharField(blank=True, max_length=128, null=True, verbose_name='事件内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindexmodel')),
            ],
            options={
                'db_table': 'pdu_event',
            },
        ),
        migrations.DeleteModel(
            name='PduAlarmModel',
        ),
    ]
