# Generated by Django 4.2.7 on 2023-11-10 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0006_pdualarmmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PduUutModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_sn', models.CharField(max_length=64, null=True, verbose_name='序列号')),
                ('dev_type', models.CharField(max_length=64, null=True, verbose_name='设备型号')),
                ('idc_name', models.CharField(max_length=64, null=True, verbose_name='数据中心')),
                ('room_name', models.CharField(max_length=64, null=True, verbose_name='机房名称')),
                ('cabinet_name', models.CharField(max_length=64, null=True, verbose_name='机柜名称')),
                ('dev_position', models.CharField(max_length=64, null=True, verbose_name='设备位置')),
                ('qrcode', models.CharField(max_length=256, null=True, verbose_name='二维码内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindexmodel')),
            ],
            options={
                'db_table': 'pdu_uut',
            },
        ),
        migrations.CreateModel(
            name='PduThresholdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.PositiveSmallIntegerField(default=0)),
                ('subtopic', models.PositiveSmallIntegerField(default=0)),
                ('indexes', models.PositiveSmallIntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindexmodel')),
            ],
            options={
                'db_table': 'pdu_threshold',
            },
        ),
        migrations.CreateModel(
            name='PduDevModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_type', models.CharField(max_length=64, null=True, verbose_name='设备型号')),
                ('dev_spec', models.PositiveSmallIntegerField(default=0, verbose_name='设备规格')),
                ('dev_mode', models.PositiveSmallIntegerField(default=0, verbose_name='设备模式')),
                ('line_num', models.PositiveSmallIntegerField(default=1, verbose_name='相数量')),
                ('loop_num', models.PositiveSmallIntegerField(default=0, verbose_name='回路数量')),
                ('output_num', models.PositiveSmallIntegerField(default=0, verbose_name='输出位数量')),
                ('sw_version', models.CharField(max_length=64, null=True, verbose_name='软件版本')),
                ('ip_v6', models.CharField(max_length=64, null=True, verbose_name='ip_v6')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindexmodel')),
            ],
            options={
                'db_table': 'pdu_dev',
            },
        ),
    ]
