# Generated by Django 4.2.7 on 2023-11-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0008_rename_name_cabinetindexmodel_cabinet_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackIndexModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rack_name', models.CharField(max_length=256, verbose_name='机架名称')),
                ('company', models.CharField(max_length=256, verbose_name='所属公司')),
                ('is_disabled', models.PositiveSmallIntegerField(default=0, verbose_name='禁用')),
                ('u_address', models.PositiveSmallIntegerField(default=0, verbose_name='U位位置')),
                ('u_height', models.PositiveSmallIntegerField(default=42, verbose_name='U位高度')),
                ('a_port', models.PositiveSmallIntegerField(default=0, verbose_name='A路端口号')),
                ('b_port', models.PositiveSmallIntegerField(default=0, verbose_name='B路端口号')),
                ('remarks', models.CharField(max_length=64, null=True, verbose_name='备注')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinetindexmodel')),
            ],
            options={
                'db_table': 'rack_index',
            },
        ),
    ]
