# Generated by Django 4.2.7 on 2023-11-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0002_alter_rackindexmodel_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rackhdamodel',
            old_name='cabinet',
            new_name='rack',
        ),
    ]
