# Generated by Django 4.2.7 on 2023-12-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdcIndexModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idc_name', models.CharField(max_length=256, verbose_name='IDC名称')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'idc_index',
            },
        ),
    ]
