# Generated by Django 4.2.7 on 2023-11-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetIndexModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rid', models.IntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=256, verbose_name='机柜名称')),
                ('pow_capacity', models.PositiveSmallIntegerField(default=6, verbose_name='电力容量（KVA）')),
                ('pdu_box', models.PositiveSmallIntegerField(default=0, verbose_name='数据来源')),
                ('is_disabled', models.PositiveSmallIntegerField(default=0, verbose_name='禁用')),
                ('height', models.PositiveSmallIntegerField(default=42, verbose_name='高度')),
                ('location', models.CharField(max_length=64, null=True, verbose_name='位置')),
                ('group_name', models.CharField(max_length=64, null=True, verbose_name='组名')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cabinet_index',
            },
        ),
    ]
