# Generated by Django 4.2.7 on 2023-11-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetPduModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_pdu_id', models.IntegerField(default=0)),
                ('b_pdu_id', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinetindexmodel')),
            ],
            options={
                'db_table': 'cabinet_pdu',
            },
        ),
        migrations.CreateModel(
            name='CabinetBoxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_box_id', models.IntegerField(default=0)),
                ('a_box_outlet', models.PositiveSmallIntegerField(default=0)),
                ('b_box_id', models.IntegerField(default=0)),
                ('b_box_outlet', models.PositiveSmallIntegerField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinetindexmodel')),
            ],
            options={
                'db_table': 'cabinet_box',
            },
        ),
    ]
