# Generated by Django 4.2.7 on 2023-11-24 05:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_cabinethdamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetdatamodel',
            name='active_power',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabinetdatamodel',
            name='apparent_power',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabinetdatamodel',
            name='overhead',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='cabinetdatamodel',
            name='power_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='cabinetdatamodel',
            name='total_ele',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabinethdamodel',
            name='active_power',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabinethdamodel',
            name='apparent_power',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabinethdamodel',
            name='power_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='cabinethdamodel',
            name='total_ele',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=10),
        ),
    ]
