# Generated by Django 4.2.7 on 2023-11-24 05:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_alter_cabinetdatamodel_active_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinethdamodel',
            name='overhead',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4),
        ),
    ]
