# Generated by Django 3.2.12 on 2023-09-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PduIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('dev_key', models.CharField(max_length=64, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pdu_index',
            },
        ),
        migrations.CreateModel(
            name='PduAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_status', models.CharField(blank=True, max_length=64, null=True, verbose_name='报警类型')),
                ('alarm_content', models.CharField(blank=True, max_length=64, null=True, verbose_name='报警内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pdu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindex')),
            ],
            options={
                'db_table': 'pdu_alarm',
            },
        ),
    ]
