# Generated by Django 3.2.12 on 2023-09-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('run_status', models.PositiveSmallIntegerField(default=0, verbose_name='运行状态')),
                ('current_alarm', models.CharField(max_length=256, null=True, verbose_name='当前报警')),
                ('dev_key', models.CharField(max_length=64, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pdu_index',
            },
        ),
        migrations.CreateModel(
            name='Uut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_sn', models.CharField(max_length=64, null=True, verbose_name='序列号')),
                ('dev_type', models.CharField(max_length=64, null=True, verbose_name='设备型号')),
                ('room_name', models.CharField(max_length=64, null=True, verbose_name='机房名称')),
                ('dev_position', models.CharField(max_length=64, null=True, verbose_name='设备位置')),
                ('qrcode', models.CharField(max_length=256, null=True, verbose_name='二维码内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdu.index')),
            ],
            options={
                'db_table': 'pdu_uut',
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.PositiveSmallIntegerField(default=0)),
                ('subtopic', models.PositiveSmallIntegerField(default=0)),
                ('indexes', models.PositiveSmallIntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.index')),
            ],
            options={
                'db_table': 'pdu_threshold',
            },
        ),
        migrations.CreateModel(
            name='Hda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.PositiveSmallIntegerField(default=0)),
                ('indexes', models.PositiveSmallIntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.index')),
            ],
            options={
                'db_table': 'pdu_hda',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='事件类型')),
                ('event_content', models.CharField(blank=True, max_length=128, null=True, verbose_name='事件内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.index')),
            ],
            options={
                'db_table': 'pdu_event',
            },
        ),
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_type', models.CharField(max_length=64, null=True, verbose_name='设备型号')),
                ('dev_spec', models.PositiveSmallIntegerField(default=0, verbose_name='设备规格')),
                ('dev_mode', models.PositiveSmallIntegerField(default=0, verbose_name='设备模式')),
                ('line_num', models.PositiveSmallIntegerField(default=1, verbose_name='相数量')),
                ('loop_num', models.PositiveSmallIntegerField(default=0, verbose_name='回路数量')),
                ('output_num', models.PositiveSmallIntegerField(default=0, verbose_name='输出位数量')),
                ('cascade_addr', models.PositiveSmallIntegerField(default=0, verbose_name='级联地址')),
                ('sw_version', models.CharField(max_length=64, null=True, verbose_name='软件版本')),
                ('ip_v4', models.CharField(max_length=64, null=True, verbose_name='ip_v4')),
                ('ip_v6', models.CharField(max_length=64, null=True, verbose_name='ip_v6')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdu.index')),
            ],
            options={
                'db_table': 'pdu_dev',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.PositiveSmallIntegerField(default=0)),
                ('indexes', models.PositiveSmallIntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.index')),
            ],
            options={
                'db_table': 'pdu_data',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_status', models.CharField(blank=True, max_length=64, null=True, verbose_name='报警类型')),
                ('alarm_content', models.CharField(blank=True, max_length=128, null=True, verbose_name='报警内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.index')),
            ],
            options={
                'db_table': 'pdu_alarm',
            },
        ),
    ]
