# Generated by Django 3.2.12 on 2023-09-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdualarm',
            old_name='pdu_id',
            new_name='pdu',
        ),
        migrations.AlterField(
            model_name='pduindex',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PduUut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='序列号')),
                ('dev_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备型号')),
                ('room_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房名称')),
                ('dev_position', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备位置')),
                ('qrcode', models.CharField(blank=True, max_length=256, null=True, verbose_name='二维码内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('pdu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindex')),
            ],
            options={
                'db_table': 'pdu_uut',
            },
        ),
    ]
