# Generated by Django 3.2.12 on 2023-09-19 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0002_auto_20230916_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='PduDev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_status', models.PositiveSmallIntegerField(default=0, verbose_name='运行状态')),
                ('dev_type', models.CharField(max_length=64, null=True, verbose_name='设备型号')),
                ('dev_spec', models.PositiveSmallIntegerField(default=0, verbose_name='设备规格')),
                ('dev_mode', models.PositiveSmallIntegerField(default=0, verbose_name='设备模式')),
                ('line_num', models.PositiveSmallIntegerField(default=1, verbose_name='相数量')),
                ('loop_num', models.PositiveSmallIntegerField(default=0, verbose_name='回路数量')),
                ('output_num', models.PositiveSmallIntegerField(default=0, verbose_name='输出位数量')),
                ('cascade_addr', models.PositiveSmallIntegerField(default=0, verbose_name='级联地址')),
                ('sw_version', models.CharField(max_length=256, null=True, verbose_name='软件版本')),
                ('ip_v4', models.CharField(max_length=64, null=True, verbose_name='ip_v4')),
                ('ip_v6', models.CharField(max_length=64, null=True, verbose_name='ip_v6')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindex')),
            ],
            options={
                'db_table': 'pdu_dev',
            },
        ),
        migrations.DeleteModel(
            name='PduUut',
        ),
    ]
