# Generated by Django 3.2.12 on 2023-09-19 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0003_auto_20230919_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PduEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='事件类型')),
                ('event_content', models.CharField(blank=True, max_length=128, null=True, verbose_name='事件内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindex')),
            ],
            options={
                'db_table': 'pdu_event',
            },
        ),
        migrations.AlterField(
            model_name='pdualarm',
            name='alarm_content',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='报警内容'),
        ),
        migrations.DeleteModel(
            name='PduDev',
        ),
    ]
