# Generated by Django 3.2.12 on 2023-09-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0006_auto_20230919_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='PduThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.PositiveSmallIntegerField(default=0)),
                ('subtopic', models.PositiveSmallIntegerField(default=0)),
                ('indexes', models.PositiveSmallIntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.pduindex')),
            ],
            options={
                'db_table': 'pdu_threshold',
            },
        ),
        migrations.DeleteModel(
            name='PduData',
        ),
    ]
