# Generated by Django 3.2.12 on 2023-09-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0007_auto_20230919_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PduIndex',
            new_name='Index',
        ),
        migrations.RemoveField(
            model_name='pduthreshold',
            name='pdu',
        ),
        migrations.DeleteModel(
            name='PduAlarm',
        ),
        migrations.DeleteModel(
            name='PduThreshold',
        ),
    ]
