# Generated by Django 3.2.12 on 2023-09-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdu', '0009_uut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_status', models.CharField(blank=True, max_length=64, null=True, verbose_name='报警类型')),
                ('alarm_content', models.CharField(blank=True, max_length=128, null=True, verbose_name='报警内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdu.index')),
            ],
            options={
                'db_table': 'pdu_alarm',
            },
        ),
    ]
