# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: north.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnorth.proto\x12\x05hello\"\x10\n\x0ePduKeysRequest\"\x1c\n\x0cPduKeysReply\x12\x0c\n\x04keys\x18\x01 \x01(\t\"\x1d\n\x0ePduMetaRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"*\n\x0cPduMetaReply\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2q\n\x03Pdu\x12\x34\n\x04Keys\x12\x15.hello.PduKeysRequest\x1a\x13.hello.PduKeysReply\"\x00\x12\x34\n\x04Meta\x12\x15.hello.PduMetaRequest\x1a\x13.hello.PduMetaReply\"\x00\x32?\n\x07Greeter\x12\x34\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'north_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PDUKEYSREQUEST']._serialized_start=22
  _globals['_PDUKEYSREQUEST']._serialized_end=38
  _globals['_PDUKEYSREPLY']._serialized_start=40
  _globals['_PDUKEYSREPLY']._serialized_end=68
  _globals['_PDUMETAREQUEST']._serialized_start=70
  _globals['_PDUMETAREQUEST']._serialized_end=99
  _globals['_PDUMETAREPLY']._serialized_start=101
  _globals['_PDUMETAREPLY']._serialized_end=143
  _globals['_HELLOREQUEST']._serialized_start=145
  _globals['_HELLOREQUEST']._serialized_end=173
  _globals['_HELLOREPLY']._serialized_start=175
  _globals['_HELLOREPLY']._serialized_end=204
  _globals['_PDU']._serialized_start=206
  _globals['_PDU']._serialized_end=319
  _globals['_GREETER']._serialized_start=321
  _globals['_GREETER']._serialized_end=384
# @@protoc_insertion_point(module_scope)
