# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import north_pb2 as north__pb2


class PduStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Keys = channel.unary_unary(
                '/hello.Pdu/Keys',
                request_serializer=north__pb2.PduKeysRequest.SerializeToString,
                response_deserializer=north__pb2.PduKeysReply.FromString,
                )
        self.Meta = channel.unary_unary(
                '/hello.Pdu/Meta',
                request_serializer=north__pb2.PduMetaRequest.SerializeToString,
                response_deserializer=north__pb2.PduMetaReply.FromString,
                )


class PduServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Keys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Meta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PduServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Keys': grpc.unary_unary_rpc_method_handler(
                    servicer.Keys,
                    request_deserializer=north__pb2.PduKeysRequest.FromString,
                    response_serializer=north__pb2.PduKeysReply.SerializeToString,
            ),
            'Meta': grpc.unary_unary_rpc_method_handler(
                    servicer.Meta,
                    request_deserializer=north__pb2.PduMetaRequest.FromString,
                    response_serializer=north__pb2.PduMetaReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.Pdu', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pdu(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Keys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.Pdu/Keys',
            north__pb2.PduKeysRequest.SerializeToString,
            north__pb2.PduKeysReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Meta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.Pdu/Meta',
            north__pb2.PduMetaRequest.SerializeToString,
            north__pb2.PduMetaReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hello.Greeter/SayHello',
                request_serializer=north__pb2.HelloRequest.SerializeToString,
                response_deserializer=north__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=north__pb2.HelloRequest.FromString,
                    response_serializer=north__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.Greeter/SayHello',
            north__pb2.HelloRequest.SerializeToString,
            north__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
