# Generated by Django 3.2.12 on 2023-10-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rid', models.IntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=256, null=True, verbose_name='机柜名称')),
                ('pow_capacity', models.PositiveSmallIntegerField(default=6, verbose_name='电力容量（KVA）')),
                ('pdu_box', models.PositiveSmallIntegerField(default=0, verbose_name='数据来源')),
                ('is_disabled', models.PositiveSmallIntegerField(default=0, verbose_name='禁用')),
                ('height', models.PositiveSmallIntegerField(default=42, verbose_name='高度')),
                ('location', models.CharField(max_length=64, null=True, verbose_name='位置')),
                ('group_name', models.CharField(max_length=64, null=True, verbose_name='组名')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cabinet_index',
            },
        ),
        migrations.CreateModel(
            name='PduBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.PositiveSmallIntegerField(default=0)),
                ('pdu_id', models.IntegerField(default=0)),
                ('box_id', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.index')),
            ],
            options={
                'db_table': 'cabinet_pdu_box',
            },
        ),
        migrations.CreateModel(
            name='Hda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparent_power', models.FloatField(default=0)),
                ('active_power', models.FloatField(default=0)),
                ('pf', models.FloatField(default=0)),
                ('ele', models.FloatField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.index')),
            ],
            options={
                'db_table': 'cabinet_hda',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparent_power', models.FloatField(default=0)),
                ('active_power', models.FloatField(default=0)),
                ('overhead', models.FloatField(default=0)),
                ('pf', models.FloatField(default=0)),
                ('ele', models.FloatField(default=0)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.index')),
            ],
            options={
                'db_table': 'cabinet_data',
            },
        ),
    ]
